// My projects data - matches schema.ts structure
export const allProducts = [
  {
    id: 1,
    name: "Real-Time Chat Application",
    slug: "real-time-chat-application",
    tagline: "Real-time messaging with image sharing and presence",
    description:
      "A real-time chat application built using WebSockets that supports instant messaging, image sharing, authentication, and online/offline user status.",
    websiteUrl: "https://mern-chat-app-client-six.vercel.app/",
    tags: ["React", "Node.js", "WebSocket", "MongoDB"],
    createdAt: new Date("2024-02-10"),
    approvedAt: new Date("2024-02-12"),
    status: "approved" as const,
    submittedBy: "hamza036513@gmail.com",
    voteCount: 0,
  },
  {
    id: 2,
    name: "E-Commerce Store (JogKar)",
    slug: "e-commerce-store-jogkar",
    tagline: "Full-stack e-commerce platform with secure payments",
    description:
      "A full-stack e-commerce application featuring product management, user authentication, cloud image uploads, and Stripe payment integration.",
    websiteUrl: "https://e-commerce-store-clientside.vercel.app/",
    tags: ["React", "Redux Toolkit", "Node.js", "MongoDB", "Stripe"],
    createdAt: new Date("2024-03-05"),
    approvedAt: new Date("2024-03-08"),
    status: "approved" as const,
    submittedBy: "hamza036513@gmail.com",
    voteCount: 0,
  },
  {
    id: 3,
    name: "Animated Landing Page",
    slug: "animated-landing-page-gsap",
    tagline: "High-performance animated landing page",
    description:
      "An interactive landing page built with GSAP featuring smooth scroll-based animations, video synchronization, and performance-optimized transitions.",
    websiteUrl: "https://mojito-gsap-omega.vercel.app/",
    tags: ["React", "GSAP", "UI/UX"],
    createdAt: new Date("2024-04-01"),
    approvedAt: new Date("2024-04-02"),
    status: "approved" as const,
    submittedBy: "hamza036513@gmail.com",
    voteCount: 0,
  },
  {
    id: 4,
    name: "Developer Portfolio",
    slug: "developer-portfolio",
    tagline: "Personal portfolio showcasing projects and skills",
    description:
      "A modern, responsive developer portfolio showcasing full-stack projects, technical skills, and professional experience.",
    websiteUrl: "https://portfolio-chi-seven-267nhn5x4p.vercel.app",
    tags: ["React", "Tailwind CSS", "Responsive Design"],
    createdAt: new Date("2024-04-15"),
    approvedAt: new Date("2024-04-16"),
    status: "approved" as const,
    submittedBy: "hamza036513@gmail.com",
    voteCount: 0,
  },
  {
    id: 5,
    name: "Hand Gesture Controller",
    slug: "hand-gesture-controller",
    tagline: "Control your system using real-time hand gestures",
    description:
      "A computer vision-based system that uses real-time hand tracking to control mouse movement, clicks, scrolling, media playback, and system volume without physical input devices.",
    websiteUrl: "https://github.com/Hamzaa09/Hand-Gesture-Controller",
    tags: [
      "Python",
      "OpenCV",
      "MediaPipe",
      "Computer Vision",
      "Gesture Recognition",
    ],
    createdAt: new Date("2025-01-01"),
    approvedAt: new Date("2025-01-01"),
    status: "approved" as const,
    submittedBy: "hamza036513@gmail.com",
    voteCount: 0,
  },
];
